import Head from 'next/head';
import { HomePage } from '../src/components/home/home-page';

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json'); //this is how get data , import data file path , and tell com returnback what u nid
  return {
    props: {
      data: events_categories,  //what u want must create a conts first (conts is mean tell computer what your purpose. than return back what u want  )
    },
  };
}
//this function get what u nid at database , here is show
//get events categories from data.file  afterthat show at homepage frontend 